name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo https://github.com/oneapi-src/level-zero/releases/download/v1.12.0/level-zero_1.12.0+u22.04_amd64.deb && apt-get install -y level-zero_1.12.0+u22.04_amd64.deb
        sudo https://github.com/oneapi-src/level-zero/releases/download/v1.12.0/level-zero-devel_1.12.0+u22.04_amd64.deb && apt-get install -y level-zero-devel_1.12.0+u22.04_amd64.deb
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
